language: java

jdk:
- oraclejdk8

before_install:

- chmod +x mvnw

addons:
  sonarcloud:
    organization: "tasima-uniritter"
    #token:
    #  secure: ********* # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
